name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches: [ main, qa, develop ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_DEPLOYMENT_SA_KEY }}'

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Determine environment based on branch
      run: |
        if [[ "$GITHUB_REF_NAME" == "main" ]]; then
          echo "SECRET_NAME=API-ENV-PROD" >> $GITHUB_ENV
        elif [[ "$GITHUB_REF_NAME" == "qa" ]]; then
          echo "SECRET_NAME=API-ENV-QA" >> $GITHUB_ENV
        else
          echo "SECRET_NAME=API-ENV-DEV" >> $GITHUB_ENV
        fi

    - name: Pull env vars from Secret Manager
      run: |
        gcloud secrets versions access latest --secret=$SECRET_NAME > .env

    - name: Configure Docker
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Set service name branch name
      run: |-
        echo "SERVICE_NAME=api-${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build
      run: docker build -f Dockerfile.prod -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/api/$SERVICE_NAME:latest .

    - name: Push
      run: docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/api/$SERVICE_NAME:latest

    - name: Deploy
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image $REGION-docker.pkg.dev/$GCP_PROJECT_ID/api/$SERVICE_NAME:latest \
          --platform managed \
          --region $REGION \
          --set-env-vars="$(cat .env | tr '\n' ',' | sed 's/,$//')" \
          --allow-unauthenticated \
          --ingress all \
          --network default \
          --subnet default
